account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    # path('login/', views.user_login, name='login'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    #changing password
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    #password reset
    path('password_reset', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    #register a user
    path('register/', views.register, name='register'),
    #edit profile
    path('edit/', views.edit, name='edit'),
    #users
    path('users/', views.user_list, name='user_list'),
    path('users/follow', views.user_follow, name='user_follow'),
    path('users/<username>', views.user_detail, name='user_detail'),


]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from . import views

app_name= 'images'
urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('', views.image_list, name='list'),
    path('ranking/', views.image_ranking, name='ranking'),
]

account/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model


class Profile(models.Model):
    user = models.OneToOneField(get_user_model(),
                             on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d',
                              blank=True)

    def __str__(self):
        return f'Profile for user{self.user.username}'

class Contact(models.Model):
    user_from = models.ForeignKey(get_user_model(),
                                  related_name='rel_from_set',
                                  on_delete=models.CASCADE)
    user_to = models.ForeignKey(get_user_model(),
                                related_name='rel_to_set',
                                on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True,
                                   db_index=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'{self.user_from} follows {self.user_to}'

user_model = get_user_model()
user_model.add_to_class('following',
                        models.ManyToManyField('self',
                        through= Contact,
                        related_name='followers',
                        symmetrical=False))

account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class RegisterForm(forms.ModelForm):
    password = forms.CharField(label= 'Password',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label= 'Repeat password',
                                widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

        def clean_password2(self):
            cd = self.cleaned_data
            if cd['password'] != cd['password2']:
                raise forms.ValidationError('passwords dont match')
            return cd['password2']

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo')

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields =('first_name', 'last_name', 'email')

account/views.py
from django.shortcuts import get_object_or_404, render
from django.contrib.auth import login, authenticate

import actions
from .forms import LoginForm, RegisterForm, UserEditForm, ProfileEditForm
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from .models import Profile, Contact
from django.contrib import messages
from django.contrib.auth.models import User
from django.views.decorators.http import require_POST
from common.decorators import ajax_required
from actions.utils import create_action 
from actions.models import Action




def user_login(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                                    username = cd['username'],
                                    password = cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('authenticated')
                else:
                    return HttpResponse('disabled account')
            else:
                return HttpResponse('Invalid login')
    return render(request, 'account/login.html', {'form': form})

@login_required()
def dashboard(request):
    actions = Action.objects.exclude(user=request.user)
    following_ids = request.user.following.values_list('id', flat=True)
    print(following_ids)
    if following_ids:
        actions = actions.filter(user_id__in=following_ids)
        actions = actions.select_related('user','user__profile')\
            .prefetch_related('target')[:10]
    
    return render(request, "account/dashboard.html", {'section': 'dashboard', 'actions':actions})

def register(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(
                form.cleaned_data['password']
            )
            user.save()
            Profile.objects.create(user=user)
            create_action(user, 'has created an account')
            return render(request, 'account/register_done.html', {'user': user})
    return render(request, 'account/register.html', {'form': form})

@login_required()
def edit(request):
    user_form = UserEditForm()
    profile_form = ProfileEditForm()
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST,
                                 )
        profile_form = ProfileEditForm(instance=request.user.profile,
                                       data = request.POST,
                                       files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile updated successfully')
        else:
            messages.error(request, 'Error updating your profile')
    return render(request, 'account/edit.html', {
        'user_form':user_form,
        'profile_form':profile_form
    })

@login_required
def user_list(request):
    users = User.objects.filter(is_active=True)
    return render(request,
                    'account/user/list.html',
                    {'section':'people',
                    'users':users})

@login_required
def user_detail(request, username):
    user = get_object_or_404(User,
                            username=username,
                            is_active=True)
    return render(request,
                'account/user/detail.html',
                {'section':'people',
                'user':user})

@ajax_required
@require_POST
@login_required
def user_follow(request):
    user_id = request.POST.get('id')
    action = request.POST.get('action')
    if user_id and action :
        try:
            user = User.objects.get(id=user_id)
            if action == 'follow':
                Contact.objects.get_or_create(
                    user_from = request.user,
                    user_to = user
                )
                create_action(request.user, 'is following', user)
            else:
                Contact.objects.filter(user_from=request.user,
                                        user_to = user).delete()
            return JsonResponse({'status':'ok'})
        except User.DoesNotExist:
            return JsonResponse({'status':'error'})
    return JsonResponse({'status':'error'})

account/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">

</head>
<body>
    <div id="header">
        <span class="logo">Bookmarks</span>
        {% if request.user.is_authenticated %}
            <ul class="menu">
                <li {% if section == "dashboard" %} class="selected" {% endif %}>
                    <a href="{% url "dashboard" %}">My Dashboard</a>
                </li>
                <li {% if section == "images" %}class="selected"{% endif %}>
                    <a href="{% url "images:list" %}">Images</a>
                </li>

                <li {% if section == "people" %} class="selected" {% endif %}>
                    <a href="{% url "user_list" %}">People</a>
                </li>
            </ul>
        {% endif %}
        <span class="user">
            {% if request.user.is_authenticated %}
                Hello {{ request.user.username }},
                <a href="{% url "logout" %}">Logout</a>
            {% else %}div
                <a href="{% url "login" %}">Log-in</a>
            {% endif %}
        </span>
    </div>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">
                {{ message|safe }}
                <a href="#" class="close">x</a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"></script>
    <script>
    var csrftoken = Cookies.get('csrftoken');
    function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
    beforeSend: function(xhr, settings) {
    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
    xhr.setRequestHeader("X-CSRFToken", csrftoken);
    }
    }
    });
        $(document).ready(function(){
        {% block domready %}
        {% endblock %}
        });
    </script>
</body>
</html>